# gitversion will change the version number
version: x-{build}

platform: Any CPU
configuration: Release
os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

environment:
  COVERALLS_REPO_TOKEN:
    secure: j4sELCwhVRRjNXFVhjPZjdG4y2itz8jrExhlyDU/lTiLlRQ/P4brB69MGQRFBQae
  snk_secret:
    secure: 5QzEIgiDqTIrZruPaIQIvTlNMl5BZ7TGEps7ALyBfHE=

# tools we need for bulding/testing/deploying
install:
  - choco install gitversion.portable -pre -y
  #- choco install docfx
  # No longer signing the assembly
  #- nuget install secure-file -ExcludeVersion
  #- if defined snk_secret secure-file\tools\secure-file -decrypt src\ipfs.ci.snk.enc -secret %snk_secret% -out src\ipfs.dev.snk

pull_requests:
  do_not_increment_build_number: true

# gitversion will change the assembly info
assembly_info:
  patch: false

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

before_build:
  - nuget restore
  - ls packages

# Build documentation in doc\_site
  - ps: Test-Path ./packages/msdn.4.5.2.0.1.0-alpha-1611021200/content/msdn.4.5.2.zip
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - .\tools\docfx\docfx metadata doc\docfx.json
  - .\tools\docfx\docfx build doc\docfx.json
  - appveyor PushArtifact "doc\api\Ipfs.Base32.yml"

# Determine the version
  - ps: gitversion /output buildserver /updateAssemblyInfo >gitversion.log

build:
  project: IpfsCore.sln
  publish_nuget: false
  verbosity: minimal

after_build:
  - .\tools\docfx\docfx metadata doc\docfx.json
  - .\tools\docfx\docfx build doc\docfx.json
  
  
#after_build:
# Build nuget package
 # - cmd: nuget pack src\IpfsCore.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
 # - cmd: appveyor PushArtifact "Ipfs.Core.%GitVersion_NuGetVersion%.nupkg"

#after_test: 
# Generate coverage report
 #   - packages\OpenCover.4.6.210-rc\tools\OpenCover.Console.exe -register:user -filter:"+[Ipfs*]* -[*Tests]* -[Ipfs.Core]SHA3*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:test//bin/Release/Ipfs.Core.Tests.dll" -output:coverage.xml
  #  - if defined COVERALLS_REPO_TOKEN packages\coveralls.net.0.6.0\tools\csmacnz.coveralls.exe --opencover -i ./coverage.xml --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%

# publish NuGet package on tag build
#deploy:
#- provider: NuGet
 # api_key:
  #  secure: OdmGEj/l0K0ZPDmXAYx+fryCzV012eTrM29ALBuL0waxvwLvrufdDXiI+1iNhWEG
  #on:
   # appveyor_repo_tag: true
